create table if not exists public.manual_positions (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    ticker text not null,
    strategy text not null,
    expiration date not null,
    long_strike numeric not null,
    short_strike numeric not null,
    entry_price numeric not null,
    quantity integer not null default 1,
    status text not null default 'open',
    note text
);

create index if not exists manual_positions_status_idx
    on public.manual_positions(status);

create index if not exists manual_positions_ticker_expiration_idx
    on public.manual_positions(ticker, expiration);
