create table if not exists public.alpaca_paper_orders (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    scan_time timestamptz not null,
    scan_time_est text,
    order_id text,
    client_order_id text,
    ticker text,
    strategy text,
    expiration date,
    setup_score integer,
    entry_type text,
    limit_price numeric,
    quantity integer,
    order_class text,
    symbol text,
    status text,
    message text
);

create index if not exists alpaca_paper_orders_scan_time_idx
    on public.alpaca_paper_orders(scan_time desc);

create unique index if not exists alpaca_paper_orders_client_order_id_idx
    on public.alpaca_paper_orders(client_order_id)
    where client_order_id is not null;

