create table if not exists public.alpaca_paper_position_snapshots (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    alpaca_paper_order_id bigint references public.alpaca_paper_orders(id) on delete cascade,
    snapshot_time timestamptz not null,
    snapshot_time_est text,
    order_id text,
    client_order_id text,
    ticker text,
    strategy text,
    expiration date,
    entry_type text,
    limit_price numeric,
    quantity integer,
    current_value numeric,
    unrealized_pnl numeric,
    unrealized_pnl_percent numeric,
    matched_legs integer,
    total_legs integer,
    leg_key text
);

create index if not exists alpaca_paper_position_snapshots_time_idx
    on public.alpaca_paper_position_snapshots(snapshot_time desc);

create index if not exists alpaca_paper_position_snapshots_order_idx
    on public.alpaca_paper_position_snapshots(alpaca_paper_order_id);

create index if not exists alpaca_paper_position_snapshots_ticker_idx
    on public.alpaca_paper_position_snapshots(ticker, expiration);
