create table if not exists public.trade_snapshots (
    id bigint generated by default as identity primary key,
    scan_history_id bigint not null references public.scan_history(id) on delete cascade,
    snapshot_time timestamptz not null,
    snapshot_time_est text,
    ticker text not null,
    strategy text not null,
    expiration date not null,
    dte integer,
    underlying_price numeric,
    current_spread_mark numeric,
    unrealized_pnl numeric,
    pnl_percent_of_max_profit numeric,
    pnl_percent_of_max_risk numeric,
    exit_signal text,
    created_at timestamptz not null default now()
);

create index if not exists trade_snapshots_scan_history_id_idx
    on public.trade_snapshots(scan_history_id);

create index if not exists trade_snapshots_snapshot_time_idx
    on public.trade_snapshots(snapshot_time desc);

create index if not exists trade_snapshots_ticker_expiration_idx
    on public.trade_snapshots(ticker, expiration);

alter table public.scan_history
    add column if not exists highest_unrealized_pnl numeric,
    add column if not exists lowest_unrealized_pnl numeric;
